name: digital analytics
favicon: null
layout_spectrum: 0.49637
typography_spectrum: 0.36557
title: DIGITAL ANALYTICS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62726217-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#149c98'
    - '#d45202'
    - '#e99317'
    - '#084541'
    - '#31e7ea'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
