name: digital analytics
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59562
title: DIGITAL ANALYTICS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62726217-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#149c98'
    - '#d45202'
    - '#e99317'
    - '#084541'
    - '#31e7ea'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
