name: digital analytics
favicon: null
layout_spectrum: 0.7496887680608779
typography_spectrum: 0.13997723278589547
title: digital analytics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62726217-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8602399465162307
  lightness: 0.012528392719104886
  saturation: 0.15423701843246818
  rhythmicContrast: 0.35500365402549505
purpose: []
