name: digital analytics
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65752
title: DIGITAL ANALYTICS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62726217-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#149c98'
    - '#d45202'
    - '#e99317'
    - '#084541'
    - '#31e7ea'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
