title: DIGITAL ANALYTICS
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5075885
  brandStrength: 0
  lightness: 0.4983137
  brandColors:
    - '#FFFFFF'
    - '#F57921'
    - '#221E1F'
    - '#434041'
    - '#C7C5C6'
  rhythmicContrast: 0.5126476
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-62726217-2
  facebook: null
favicon: null
name: digital analytics
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1104553
layout_spectrum: 0.648398
