name: Karlnorling.com
favicon: null
layout_spectrum: 0.42061
typography_spectrum: 0.15136
title: DIGITAL ANALYTICS
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62726217-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#F57921'
    - '#221E1F'
    - '#434041'
    - '#C7C5C6'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
