title: DIGITAL ANALYTICS
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4780776
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#010100'
    - '#F34308'
    - '#912805'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-62726217-2
  facebook: null
favicon: null
name: digital analytics
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3195615
layout_spectrum: 0.9131535
