title: DIGITAL ANALYTICS
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0
  rhythmicContrast: 0.5
  brandColors:
    - '#FFFFFF'
    - '#F57921'
    - '#221E1F'
    - '#434041'
    - '#C7C5C6'
  lightness: 0.6875
cta:
  bucket: null
  version: null
  domain: null
name: Karlnorling.com
favicon: null
analytics:
  twitter: null
  google: UA-62726217-2
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3602151
layout_spectrum: 0.6379929
